# Nombre de la aplicación
spring.application.name=servicios-web-estudiantes

# Puerto del servidor
server.port=9090

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/universidad
spring.datasource.username=admin
spring.datasource.password=admin1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# update: crea o actualiza tablas automáticamente
# Útil en desarrollo
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Formatear SQL mostrado
spring.jpa.properties.hibernate.format_sql=true

# Desactivar open in view como buena práctica
spring.jpa.open-in-view=false

# Si se crea una tabla de manera manual y no queremos que hibernate la modifique
# cambiamos update por validate
# spring.jpa.hibernate.ddl-auto=validate
